{% set name = "vega-python-sdk" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vegaprotocol/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 25b9844f649c5fab054a0e458f7d7216462d6b06085ed67242e15c02a0a10875

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - poetry
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - bip-utils >=2.7.1
    - grpcio-tools >=1.59.0
    - protoc-gen-openapiv2 >=0.0.1
    - python >={{ python_min }}

test:
  imports:
    - vega
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/vegaprotocol/vega-python-sdk
  summary: 'A set of helpful tools for building software interacting with Vega Protocol networks in Python.'
  description: |
    A set of helpful tools for building software interacting with Vega Protocol networks in Python.
    Initially contains a client for signing/submitting transactions, which can be found in vega.client.
    For signing and submitting, the client requires a BIP39 recovery phrase to seed the client.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
